-- STEP 7: score stored forecast results against test-only actuals; never rerun forecasting.
alter table core.forecast_setting add column if not exists champion_metric text not null default 'WAPE' check(champion_metric in ('WAPE','MAPE','RMSE','MAE'));
alter table core.forecast_setting add column if not exists reference_model_id text not null default 'MA_3M';
create table if not exists core.backtest_run(backtest_run_id uuid primary key default gen_random_uuid(),forecast_run_id uuid not null references core.forecast_run(run_id),test_start date not null,test_end date not null,metric text not null,status text not null check(status in('RUNNING','SUCCESS','FAILED')),started_at timestamptz not null default now(),finished_at timestamptz,triggered_by uuid references auth.users(id),message text);
create table if not exists core.model_performance(backtest_run_id uuid not null references core.backtest_run(backtest_run_id) on delete cascade,run_id uuid not null,model_id text not null,model_version text not null,item_id text not null,n_periods integer not null,wape numeric,mape numeric,bias numeric,rmse numeric,mae numeric,baseline_improvement numeric,rank integer,calculation_status text not null,reason_code text,calculated_at timestamptz not null default now(),primary key(backtest_run_id,model_id,item_id));
create table if not exists core.champion_model_history(champion_history_id uuid primary key default gen_random_uuid(),backtest_run_id uuid references core.backtest_run(backtest_run_id),item_id text not null,champion_model_id text,model_version text,champion_metric text not null,champion_metric_value numeric,wape numeric,mape numeric,bias numeric,rmse numeric,mae numeric,candidate_performance jsonb not null,selection_reason text,selection_method text not null check(selection_method in('AUTO','MANUAL')),selected_at timestamptz not null default now(),selected_by uuid references auth.users(id));

create or replace function core.run_backtest(target_forecast_run uuid)
returns uuid language plpgsql security definer set search_path=core,analytics,pg_temp as $$
declare b core.backtest_run; s core.forecast_setting;
begin
 if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if; select * into s from core.forecast_setting where active limit 1;
 insert into core.backtest_run(forecast_run_id,test_start,test_end,metric,status,triggered_by) values(target_forecast_run,s.test_start,s.test_end,s.champion_metric,'RUNNING',auth.uid()) returning * into b;
 insert into core.model_performance(backtest_run_id,run_id,model_id,model_version,item_id,n_periods,wape,mape,bias,rmse,mae,calculation_status,reason_code)
 with matched as(select f.run_id,f.model_id,f.model_version,f.item_id,f.period,f.predicted_qty,a.actual_qty from core.forecast_result f join core.v_test_actual a on a.item_id=f.item_id and a.period_start=f.period where f.run_id=target_forecast_run and a.use_date between s.test_start and s.test_end),
 metric as(select run_id,model_id,model_version,item_id,count(*) n_periods,sum(abs(actual_qty)) actual_sum,avg(abs(predicted_qty-actual_qty)/nullif(abs(actual_qty),0)) filter(where actual_qty<>0) mape,avg(predicted_qty-actual_qty) bias,sqrt(avg(power(predicted_qty-actual_qty,2))) rmse,avg(abs(predicted_qty-actual_qty)) mae,sum(abs(predicted_qty-actual_qty)) abs_error from matched group by 1,2,3,4)
 select b.backtest_run_id,run_id,model_id,model_version,item_id,n_periods,case when actual_sum=0 then null else abs_error/actual_sum end,mape,bias,rmse,mae,case when actual_sum=0 then 'UNAVAILABLE' else 'SUCCESS' end,case when actual_sum=0 then 'ZERO_ACTUAL_SUM' when mape is null then 'MAPE_ZERO_DENOMINATOR' end from metric;
 update core.model_performance p set baseline_improvement=case when ref.wape is null or ref.wape=0 or p.wape is null then null else (ref.wape-p.wape)/ref.wape end from core.model_performance ref where p.backtest_run_id=b.backtest_run_id and ref.backtest_run_id=b.backtest_run_id and ref.item_id=p.item_id and ref.model_id=s.reference_model_id;
 with ranked as(select *,row_number() over(partition by item_id order by case s.champion_metric when 'WAPE' then wape when 'MAPE' then mape when 'RMSE' then rmse else mae end nulls last,abs(bias) nulls last,rmse nulls last,model_id) r from core.model_performance where backtest_run_id=b.backtest_run_id and calculation_status='SUCCESS') update core.model_performance p set rank=r.r from ranked r where p.backtest_run_id=b.backtest_run_id and p.model_id=r.model_id and p.item_id=r.item_id;
 insert into core.champion_model_history(backtest_run_id,item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,mae,candidate_performance,selection_reason,selection_method,selected_by)
 select b.backtest_run_id,p.item_id,p.model_id,p.model_version,s.champion_metric,case s.champion_metric when 'WAPE' then p.wape when 'MAPE' then p.mape when 'RMSE' then p.rmse else p.mae end,p.wape,p.mape,p.bias,p.rmse,p.mae,(select jsonb_agg(jsonb_build_object('model_id',x.model_id,'wape',x.wape,'mape',x.mape,'bias',x.bias,'rmse',x.rmse,'mae',x.mae,'rank',x.rank,'status',x.calculation_status)) from core.model_performance x where x.backtest_run_id=b.backtest_run_id and x.item_id=p.item_id),'LOWEST_CONFIGURED_METRIC; ties: ABS_BIAS, RMSE, MODEL_ID','AUTO',auth.uid() from core.model_performance p where p.backtest_run_id=b.backtest_run_id and p.rank=1;
 update core.backtest_run set status='SUCCESS',finished_at=now() where backtest_run_id=b.backtest_run_id; return b.backtest_run_id;
exception when others then if b.backtest_run_id is not null then update core.backtest_run set status='FAILED',finished_at=now(),message=sqlerrm where backtest_run_id=b.backtest_run_id; end if; raise; end $$;
create or replace function core.set_manual_champion(target_backtest uuid,target_item text,target_model text,reason_text text) returns void language plpgsql security definer set search_path=core,pg_temp as $$ declare p core.model_performance; begin if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if; if coalesce(trim(reason_text),'')='' then raise exception 'MANUAL_REASON_REQUIRED'; end if; select * into p from core.model_performance where backtest_run_id=target_backtest and item_id=target_item and model_id=target_model; if not found then raise exception 'PERFORMANCE_NOT_FOUND'; end if; insert into core.champion_model_history(backtest_run_id,item_id,champion_model_id,model_version,champion_metric,champion_metric_value,wape,mape,bias,rmse,mae,candidate_performance,selection_reason,selection_method,selected_by) select target_backtest,target_item,target_model,p.model_version,'WAPE',p.wape,p.wape,p.mape,p.bias,p.rmse,p.mae,(select jsonb_agg(to_jsonb(x)) from core.model_performance x where x.backtest_run_id=target_backtest and x.item_id=target_item),reason_text,'MANUAL',auth.uid(); insert into core.audit_log(actor,action,target_type,target_id,after) values(auth.uid(),'CHAMPION_MANUAL_SELECTED','champion_model',target_item,jsonb_build_object('model_id',target_model,'reason',reason_text)); end $$;
create or replace view analytics.v_model_performance with(security_invoker=true) as select * from core.model_performance;
create or replace view analytics.v_champion_model with(security_invoker=true) as select distinct on(item_id) * from core.champion_model_history order by item_id,selected_at desc;
create or replace view analytics.v_backtest_run with(security_invoker=true) as select * from core.backtest_run;
revoke all on core.backtest_run,core.model_performance,core.champion_model_history from anon; grant select on analytics.v_model_performance,analytics.v_champion_model,analytics.v_backtest_run to authenticated; grant execute on function core.run_backtest(uuid),core.set_manual_champion(uuid,text,text,text) to authenticated;
do $$ declare t text; begin foreach t in array array['backtest_run','model_performance','champion_model_history'] loop execute format('alter table core.%I enable row level security',t); execute format('grant select,insert,update,delete on core.%I to authenticated',t); execute format('create policy backtest_active_select on core.%I for select to authenticated using (exists(select 1 from core.app_user u where u.user_id=(select auth.uid()) and u.active))',t); execute format('create policy backtest_admin_all on core.%I for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()))',t); end loop; end $$;
