-- STEP 2: Auth profile, RBAC, and audit trail.
-- Existing SCM calculation views and formulas are intentionally unchanged.

create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text,
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id);
create index if not exists audit_log_at_idx on core.audit_log(at desc);

create or replace function core.set_updated_at()
returns trigger
language plpgsql
set search_path = core, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
  before update on core.app_user
  for each row execute function core.set_updated_at();

create or replace function core.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
begin
  insert into core.app_user (user_id, email, name, department)
  values (
    new.id,
    coalesce(new.email, ''),
    new.raw_user_meta_data ->> 'name',
    new.raw_user_meta_data ->> 'department'
  )
  on conflict (user_id) do update
    set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function core.handle_new_auth_user();

insert into core.app_user (user_id, email, name, department)
select id, coalesce(email, ''), raw_user_meta_data ->> 'name', raw_user_meta_data ->> 'department'
from auth.users
on conflict (user_id) do update set email = excluded.email;

create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = core, pg_temp
as $$
  select exists (
    select 1
    from core.app_user
    where user_id = auth.uid()
      and role = 'ADMIN'
      and active = true
  );
$$;

revoke all on function core.is_admin() from public;
grant execute on function core.is_admin() to authenticated;

create or replace function core.touch_last_login()
returns void
language sql
security definer
set search_path = core, pg_temp
as $$
  update core.app_user
     set last_login_at = now(), updated_at = now()
   where user_id = auth.uid()
     and active = true;
$$;

revoke all on function core.touch_last_login() from public;
grant execute on function core.touch_last_login() to authenticated;

create or replace function core.audit_app_user_change()
returns trigger
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
begin
  if old.role is distinct from new.role then
    insert into core.audit_log(actor, action, target_type, target_id, before, after)
    values (
      auth.uid(), 'USER_ROLE_CHANGED', 'app_user', new.user_id::text,
      jsonb_build_object('role', old.role),
      jsonb_build_object('role', new.role)
    );
  end if;

  if old.active is distinct from new.active then
    insert into core.audit_log(actor, action, target_type, target_id, before, after)
    values (
      auth.uid(), case when new.active then 'USER_ACTIVATED' else 'USER_DEACTIVATED' end,
      'app_user', new.user_id::text,
      jsonb_build_object('active', old.active),
      jsonb_build_object('active', new.active)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists app_user_audit_change on core.app_user;
create trigger app_user_audit_change
  after update on core.app_user
  for each row execute function core.audit_app_user_change();

-- Remove broad policies from the existing exposed data tables.
do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where (schemaname = 'core' and tablename in ('app_user', 'audit_log', 'leadtime_plan', 'usage_profile', 'supplier_alias'))
       or (schemaname = 'public' and tablename in ('planning_runs', 'ol_demand', 'sfdc_pipeline', 'bulk_deals', 'historical_actuals', 'demand_confirmations'))
  loop
    execute format('drop policy if exists %I on %I.%I', p.policyname, p.schemaname, p.tablename);
  end loop;
end;
$$;

-- The public anon role must not access or mutate business data.
revoke all on all tables in schema core from anon;
revoke all on all tables in schema analytics from anon;
revoke all on all tables in schema raw from anon;
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema core from anon;
revoke all on all functions in schema core from anon;

grant usage on schema core, analytics to authenticated;
grant select on all tables in schema core to authenticated;
grant select on all tables in schema analytics to authenticated;
grant select on all tables in schema public to authenticated;
grant execute on function core.is_admin() to authenticated;
grant execute on function core.touch_last_login() to authenticated;

grant update on core.app_user to authenticated;
grant insert, update, delete on core.leadtime_plan, core.usage_profile to authenticated;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;

create policy app_user_select on core.app_user
  for select to authenticated
  using (active = true and user_id = auth.uid() or core.is_admin());

create policy app_user_admin_update on core.app_user
  for update to authenticated
  using (core.is_admin() and user_id <> auth.uid())
  with check (core.is_admin() and user_id <> auth.uid());

create policy audit_log_admin_select on core.audit_log
  for select to authenticated
  using (core.is_admin());

alter table core.leadtime_plan enable row level security;
alter table core.usage_profile enable row level security;

create policy leadtime_plan_user_select on core.leadtime_plan
  for select to authenticated
  using (exists (select 1 from core.app_user u where u.user_id = auth.uid() and u.active));
create policy leadtime_plan_admin_insert on core.leadtime_plan
  for insert to authenticated with check (core.is_admin());
create policy leadtime_plan_admin_update on core.leadtime_plan
  for update to authenticated using (core.is_admin()) with check (core.is_admin());
create policy leadtime_plan_admin_delete on core.leadtime_plan
  for delete to authenticated using (core.is_admin());

create policy usage_profile_user_select on core.usage_profile
  for select to authenticated
  using (exists (select 1 from core.app_user u where u.user_id = auth.uid() and u.active));
create policy usage_profile_admin_insert on core.usage_profile
  for insert to authenticated with check (core.is_admin());
create policy usage_profile_admin_update on core.usage_profile
  for update to authenticated using (core.is_admin()) with check (core.is_admin());
create policy usage_profile_admin_delete on core.usage_profile
  for delete to authenticated using (core.is_admin());

alter table core.supplier_alias enable row level security;
create policy supplier_alias_user_select on core.supplier_alias
  for select to authenticated
  using (exists (select 1 from core.app_user u where u.user_id = auth.uid() and u.active));

-- Current planning tables are readable by active users and writable by admins.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['planning_runs', 'ol_demand', 'sfdc_pipeline', 'bulk_deals', 'historical_actuals', 'demand_confirmations']
  loop
    if to_regclass(format('public.%I', table_name)) is null then
      continue;
    end if;
    execute format('alter table public.%I enable row level security', table_name);
    execute format('create policy %I on public.%I for select to authenticated using (exists (select 1 from core.app_user u where u.user_id = auth.uid() and u.active))', table_name || '_user_select', table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check (core.is_admin())', table_name || '_admin_insert', table_name);
    execute format('create policy %I on public.%I for update to authenticated using (core.is_admin()) with check (core.is_admin())', table_name || '_admin_update', table_name);
    execute format('create policy %I on public.%I for delete to authenticated using (core.is_admin())', table_name || '_admin_delete', table_name);
  end loop;
end;
$$;

alter default privileges in schema core revoke all on tables from anon;
alter default privileges in schema core grant select on tables to authenticated;
