-- STEP 4: file import staging, validation history, and batch rollback.
create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(), file_name text not null,
  import_type text not null, import_mode text not null check (import_mode in ('append','upsert','replace')),
  total_rows integer not null default 0, success_rows integer not null default 0,
  warning_rows integer not null default 0, error_rows integer not null default 0,
  status text not null default 'STAGED' check (status in ('STAGED','VALIDATED','IMPORTED','ROLLED_BACK','FAILED')),
  uploaded_by uuid not null references auth.users(id), uploaded_at timestamptz not null default now(), imported_at timestamptz,
  replace_confirmed boolean not null default false
);
create table if not exists core.import_staging (
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null, original_row jsonb not null, mapped_row jsonb, validation_status text not null default 'PENDING' check (validation_status in ('PENDING','SUCCESS','WARNING','ERROR')),
  primary key (batch_id,row_number)
);
create table if not exists core.validation_error (
  id bigint generated by default as identity primary key, batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  row_number integer not null, field_name text, error_code text not null, error_message text not null,
  severity text not null check (severity in ('WARNING','ERROR')), original_value text
);
create table if not exists core.column_mapping (
  id uuid primary key default gen_random_uuid(), import_type text not null, source_column text not null, target_column text not null,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(),
  unique(import_type, source_column)
);
create table if not exists core.import_rollback_snapshot (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references core.upload_batch(batch_id) on delete cascade,
  import_type text not null,
  row_data jsonb not null
);
create table if not exists core.forecast_stale_event (
  batch_id uuid primary key references core.upload_batch(batch_id) on delete cascade,
  reason_code text not null,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists upload_batch_uploaded_at_idx on core.upload_batch(uploaded_at desc);
create index if not exists import_staging_status_idx on core.import_staging(batch_id,validation_status);
create index if not exists validation_error_batch_idx on core.validation_error(batch_id,row_number);
create index if not exists import_rollback_snapshot_batch_idx on core.import_rollback_snapshot(batch_id);

do $$ declare t text; begin
  foreach t in array array['upload_batch','import_staging','validation_error','column_mapping','import_rollback_snapshot','forecast_stale_event'] loop
    execute format('alter table core.%I enable row level security',t);
    execute format('revoke all on core.%I from anon',t);
    execute format('grant select,insert,update,delete on core.%I to authenticated',t);
    execute format('drop policy if exists import_admin_all on core.%I',t);
    execute format('create policy import_admin_all on core.%I for all to authenticated using ((select core.is_admin())) with check ((select core.is_admin()))',t);
  end loop;
end $$;

create or replace function core.rollback_import_batch(target_batch_id uuid)
returns void language plpgsql security definer set search_path = core, raw, pg_temp as $$
declare batch core.upload_batch; snapshot record; begin
  if not core.is_admin() then raise exception 'ADMIN_REQUIRED'; end if;
  select * into batch from core.upload_batch where batch_id=target_batch_id for update;
  if not found then raise exception 'BATCH_NOT_FOUND'; end if;
  if batch.import_mode='replace' then raise exception 'REPLACE_ROLLBACK_UNSUPPORTED'; end if;
  if batch.import_type not in ('usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event') then raise exception 'UNSUPPORTED_IMPORT_TYPE'; end if;
  execute format('delete from raw.%I where batch_id = $1', batch.import_type) using target_batch_id;
  for snapshot in select row_data from core.import_rollback_snapshot where batch_id = target_batch_id loop
    execute format('insert into raw.%I select * from jsonb_populate_record(null::raw.%I, $1)', batch.import_type, batch.import_type) using snapshot.row_data;
  end loop;
  update core.upload_batch set status='ROLLED_BACK' where batch_id=target_batch_id;
end; $$;
revoke all on function core.rollback_import_batch(uuid) from public;
grant execute on function core.rollback_import_batch(uuid) to authenticated;
